"""Default product attribute catalog seeds."""

DEFAULT_ATTRIBUTE_SEEDS: list[dict] = [
    {"key": "material", "label": "Material", "aliases": ["housing material", "construction material"], "hint": "Primary material composition"},
    {"key": "length", "label": "Length", "aliases": ["overall length", "oal"], "hint": "Product length dimension"},
    {"key": "width", "label": "Width", "aliases": ["overall width"], "hint": "Product width dimension"},
    {"key": "thickness", "label": "Thickness", "aliases": ["depth", "gauge"], "hint": "Thickness or depth"},
    {"key": "height", "label": "Height", "aliases": ["overall height"], "hint": "Product height dimension"},
    {"key": "voltage", "label": "Voltage", "aliases": ["rated voltage", "input voltage"], "hint": "Electrical voltage rating"},
    {"key": "wattage", "label": "Wattage", "aliases": ["power rating", "watts"], "hint": "Power rating in watts"},
    {"key": "amperage", "label": "Amperage", "aliases": ["current rating", "amps", "amperes"], "hint": "Current rating"},
    {"key": "mounting", "label": "Mounting", "aliases": ["mount type", "mounting style"], "hint": "How the part is mounted"},
    {"key": "style", "label": "Style", "aliases": ["type", "configuration"], "hint": "Product style or configuration"},
    {"key": "color", "label": "Color", "aliases": ["finish", "colour"], "hint": "Color or finish"},
    {"key": "weight", "label": "Weight", "aliases": ["shipping weight", "net weight"], "hint": "Product weight"},
    {"key": "temperature_rating", "label": "Temperature Rating", "aliases": ["operating temperature", "temp range"], "hint": "Operating temperature range"},
    {"key": "connector_type", "label": "Connector Type", "aliases": ["connection type", "plug type"], "hint": "Electrical or fluid connector type"},
    {"key": "thread_size", "label": "Thread Size", "aliases": ["thread pitch", "npt size"], "hint": "Thread specification"},
    {"key": "pressure_rating", "label": "Pressure Rating", "aliases": ["max pressure", "psi rating"], "hint": "Maximum pressure rating"},
    {"key": "flow_rate", "label": "Flow Rate", "aliases": ["cfm", "gpm"], "hint": "Fluid or air flow rate"},
    {"key": "load_rating", "label": "Load Rating", "aliases": ["load capacity", "weight capacity"], "hint": "Maximum load or weight capacity"},
    {"key": "gear_ratio", "label": "Gear Ratio", "aliases": ["ratio"], "hint": "Gear reduction or drive ratio"},
    {"key": "series", "label": "Series", "aliases": ["product series", "model series"], "hint": "Product line or series designation"},
    {"key": "construction_features", "label": "Construction Features", "aliases": ["features", "design features"], "hint": "Notable construction or design characteristics"},
    {"key": "travel", "label": "Travel", "aliases": ["stroke", "travel distance"], "hint": "Linear or rotational travel distance"},
    {"key": "compatibility", "label": "Compatibility", "aliases": ["fits", "applications"], "hint": "Vehicle or equipment compatibility"},
    {"key": "certification", "label": "Certification", "aliases": ["standards", "dot", "sae"], "hint": "Compliance certifications"},
    {"key": "warranty", "label": "Warranty", "aliases": ["warranty period"], "hint": "Warranty terms"},
]
